name: Docs Setup
description: Setting up Rust and mdBook
runs:
  using: composite
  steps:
    - run: |
        rustup set profile minimal
        rustup toolchain install stable
        rustup default stable
        mkdir bin
        curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.14/mdbook-v0.4.14-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
        echo "$(pwd)/bin" >> $GITHUB_PATH
      shell: bash
